# docker-compose.yml or compose.yml both names are OK
# However more pref is now given to compose.yml file
# version field is now DEPRECATED & not required

services:
    dev:
        image: nish1896/reat-ts-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '4000:3000'
        volumes:
            - .:/app
            - /app/node_modules
    prod:
        image: nish1896/react-ts-prod
        build: .
        ports:
            - '3000:80'
